language: node_js
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - awscli

node_js:
  - '6'

branches:
  only:
    - master
    - develop

cache: yarn

install:
  - yarn
  - yarn global add @angular/cli

before_script:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - ng lint
  - ng test --watch=false --code-coverage
  # - ng e2e

before_deploy:
  - cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - ng build --prod

deploy:
  - provider: script
    script: ./dev/update_aws.sh $DEV_BUCKET $DEV_CF_DISTRO
    on:
      branch: develop
  - provider: script
    script: ./dev/update_aws.sh $PROD_BUCKET $PROD_CF_DISTRO
    on:
      tags: true
      branch: master
