language: node_js
sudo: true
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

node_js:
  - '6'

branches:
  only:
    - master
    - develop

cache: yarn

install:
  - yarn
  - yarn global add @angular/cli

before_script:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - ng lint
  # - ng test --watch=false --code-coverage
  # - ng e2e

before_deploy:
  - cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - ng build -prod
  - pip install awscli

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $DEV_BUCKET
    skip_cleanup: true
    acl: public_read
    local_dir: dist
    default_text_charset: 'utf-8'
    cache_control: "max-age=31536000"
    on:
      branch: develop
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $PROD_BUCKET
    skip_cleanup: true
    acl: public_read
    local_dir: dist
    default_text_charset: 'utf-8'
    cache_control: "max-age=31536000"
    on:
      branch: master

after_deploy:
  - ./dev/update_aws.sh
